server:
  port: 8501

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 111.231.60.148:10003
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.60.148:10000/starry_stars?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 1234
  data:
    redis:
      host: 111.231.60.148
      port: 10001
      password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
