server:
  port: 8500
spring:
  application:
    name: fx-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 111.231.60.148:10003
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-galaxy
          uri: lb://service-galaxy
          predicates:
            - Path=/*/mood/**
        - id: service-emotion
          uri: lb://service-emotion
          predicates:
            - Path=/*/emotion/**
        - id: service-common
          uri: lb://service-common
          predicates:
            - Path=/*/common/**
  data:
    redis:
      host: 111.231.60.148
      port: 10001
      password: 1234